version: "3.7"
services:
  item-db:
    image: mongo:3
    volumes: 
    - app-db:/data/db
  item-app:
    image: ghcr.io/regysaputra/item-app:v1
    command: sh -c "npm install && npm start"
    ports:
      - 80:8080
    working_dir: /app
volumes:
  app-db: